apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  application.properties: |-
    server.port=8080
    database.in-memory=true
    efficient.mode={{ if eq .Values.mode "direct" }}true{{ else }}false{{ end }}
    
    # Starts leaking a small number of native-memory allocations
    native-memory-leak.mode=false
    
    management.endpoints.web.exposure.include=health
