kind: PersistentVolume
apiVersion: v1
metadata:
  name: jeffrey-vol
  labels:
    type: local
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: jeffrey-console
    meta.helm.sh/release-namespace: default
spec:
  storageClassName: shared-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/tmp/jeffrey-data"