services:
  jeffrey-console:
    image: petrbouda/jeffrey:latest
    container_name: jeffrey-console
    ports:
      - "8080:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
    volumes:
      - ./config/console/application.properties:/app/config/application.properties:ro
      - jeffrey-data:/tmp/jeffrey
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - jeffrey-network
    restart: unless-stopped

  jeffrey-testapp-client:
    image: petrbouda/jeffrey-testapp-client:latest
    container_name: jeffrey-testapp-client
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
      - JDK_JAVA_OPTIONS=-agentpath:/usr/lib/async-profiler/lib/libasyncProfiler.so=start,event=ctimer,wall=10ms,loop=5m,chunksize=5m,jfrsync=default,file=%{JEFFREY_PROFILE_DIR}/profile-%t.jfr
    volumes:
      - ./config/client/application.properties:/app/config/application.properties:ro
      - jeffrey-data:/tmp/jeffrey
      - ./scripts:/scripts:ro
    command: >
      java /scripts/InitContainerScript.java ; source /tmp/jeffrey/jeffrey-testapp-client/.env && java -jar /app/runner.jar
    depends_on:
      jeffrey-testapp-direct-server:
        condition: service_healthy
      jeffrey-testapp-dom-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - jeffrey-network
    restart: unless-stopped

  jeffrey-testapp-direct-server:
    image: petrbouda/jeffrey-testapp-server:latest
    container_name: jeffrey-testapp-direct-server
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
      - JDK_JAVA_OPTIONS=-agentpath:/usr/lib/async-profiler/lib/libasyncProfiler.so=start,event=ctimer,wall=10ms,loop=5m,chunksize=5m,jfrsync=default,file=%{JEFFREY_PROFILE_DIR}/profile-%t.jfr
    volumes:
      - ./config/server-direct/application.properties:/app/config/application.properties:ro
      - jeffrey-data:/tmp/jeffrey
      - ./scripts:/scripts:ro
    command: >
      java /scripts/InitContainerScript.java ; source /tmp/jeffrey/jeffrey-testapp-direct/.env && java -jar /app/runner.jar
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - jeffrey-network
    restart: unless-stopped

  jeffrey-testapp-dom-server:
    image: petrbouda/jeffrey-testapp-server:0.2
    container_name: jeffrey-testapp-dom-server
    ports:
      - "8081:8080"
    environment:
      - SPRING_CONFIG_LOCATION=/app/config/application.properties
#      - JDK_JAVA_OPTIONS=-agentpath:/usr/lib/async-profiler/lib/libasyncProfiler.so=start,event=ctimer,wall=10ms,loop=5m,chunksize=5m,jfrsync=default,file=%{JEFFREY_PROFILE_DIR}/profile-%t.jfr
    volumes:
      - ./config/server-dom/application.properties:/app/config/application.properties:ro
      - jeffrey-data:/tmp/jeffrey
      - ./scripts:/scripts:ro
#    command: >
#      bash -c "
#          /scripts/init-jeffrey-env.sh /tmp/jeffrey/jeffrey-testapp-dom
#        "
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - jeffrey-network
    restart: unless-stopped

volumes:
  jeffrey-data:
    driver: local

networks:
  jeffrey-network:
    driver: bridge
